import { CronExpressionParser } from 'cron-parser';
import { es } from './esClient.js';
import { logActivity } from './activity.js';
import { logTimelineEvent } from './timeline.js';
import { dateOf, mapHit, nowIso, todayStr } from './util.js';

const WEEKDAYS = { SUN: 0, MON: 1, TUE: 2, WED: 3, THU: 4, FRI: 5, SAT: 6 };
const WEEKDAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

// Compute the next run timestamp strictly after `from`, preserving its time-of-day.
export function computeNextRun(recurrence_type, recurrence_value, from = new Date()) {
  const base = new Date(from);

  if (recurrence_type === 'custom_cron') {
    const interval = CronExpressionParser.parse(recurrence_value, { currentDate: base });
    return interval.next().toDate();
  }

  if (recurrence_type === 'daily') {
    const d = new Date(base);
    d.setDate(d.getDate() + 1);
    return d;
  }

  if (recurrence_type === 'weekly') {
    const wanted = recurrence_value
      .split(',')
      .map((s) => WEEKDAYS[s.trim().toUpperCase().slice(0, 3)])
      .filter((n) => n !== undefined);
    if (!wanted.length) wanted.push(base.getDay());
    for (let i = 1; i <= 7; i++) {
      const d = new Date(base);
      d.setDate(d.getDate() + i);
      if (wanted.includes(d.getDay())) return d;
    }
  }

  if (recurrence_type === 'monthly') {
    const day = Math.max(1, parseInt(recurrence_value, 10) || 1);
    const d = new Date(base);
    d.setMonth(d.getMonth() + 1, 1); // first of next month avoids overflow
    const lastDay = new Date(d.getFullYear(), d.getMonth() + 1, 0).getDate();
    d.setDate(Math.min(day, lastDay));
    return d;
  }

  // Fallback: +1 day.
  const d = new Date(base);
  d.setDate(d.getDate() + 1);
  return d;
}

// Human-readable schedule string for the Recurring tab.
export function describeSchedule(recurrence_type, recurrence_value) {
  switch (recurrence_type) {
    case 'daily': return 'Every day';
    case 'weekly': {
      const names = recurrence_value
        .split(',')
        .map((s) => WEEKDAY_NAMES[WEEKDAYS[s.trim().toUpperCase().slice(0, 3)]])
        .filter(Boolean);
      if (!names.length) return 'Weekly';
      if (names.length === 1) return `Every ${names[0]}`;
      return `Every ${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`;
    }
    case 'monthly': return `Monthly on day ${recurrence_value}`;
    case 'custom_cron': return `Cron: ${recurrence_value}`;
    default: return recurrence_value;
  }
}

// Build a concrete instance document from a rule's template and index it.
async function generateInstance(rule) {
  const payload = rule.template_payload || {};
  const now = nowIso();
  let index, document, title;

  const owner = rule.created_by || 'engineer';
  if (rule.template_type === 'maintenance') {
    index = 'maintenance';
    document = {
      environment: payload.environment || 'test',
      version: payload.version || '',
      release_version: payload.release_version || '',
      notes: payload.notes || '',
      date: todayStr(),
      created_at: now,
      tags: payload.tags || [],
      recurrence_rule_id: rule.id,
      created_by: owner,
      assigned_to: owner,
    };
    title = `Maintenance: ${document.environment} ${document.version}`.trim();
  } else {
    index = 'daily_tasks';
    document = {
      task_name: payload.task_name || 'Recurring task',
      environment: payload.environment || 'test',
      entry_time: now,
      todo_description: payload.todo_description || '',
      who_asked: payload.who_asked || 'recurrence',
      priority: payload.priority || 'medium',
      status: 'pending',
      created_at: now,
      completed_at: null,
      tags: payload.tags || [],
      parent_id: payload.parent_id || null,
      parent_type: payload.parent_type || null,
      blocks: [],
      blocked_by: [],
      recurrence_rule_id: rule.id,
      created_by: owner,
      assigned_to: payload.assigned_to || owner,
    };
    title = document.task_name;
  }

  const { _id } = await es.index({ index, document, refresh: 'wait_for' });

  await logActivity({
    entity_type: rule.template_type,
    entity_id: _id,
    action: 'created',
    reason_note: `Auto-generated by recurrence rule ${rule.id}`,
    actor: 'recurrence',
  });

  await logTimelineEvent({
    event_type: rule.template_type === 'maintenance' ? 'maintenance' : 'task',
    event_title: `↻ ${title}`,
    event_description: 'Auto-generated recurring instance.',
    related_id: _id,
    date: dateOf(now),
  });

  return _id;
}

// Find due, active rules; generate instances and roll their next_run_at forward.
export async function generateDueInstances() {
  let hits;
  try {
    const r = await es.search({
      index: 'recurrence_rules',
      size: 200,
      query: {
        bool: {
          filter: [
            { term: { active: true } },
            { range: { next_run_at: { lte: nowIso() } } },
          ],
        },
      },
    });
    hits = r.hits.hits.map(mapHit);
  } catch (e) {
    return; // index may not exist yet on first boot
  }

  for (const rule of hits) {
    try {
      await generateInstance(rule);
      // Advance from the scheduled time so cadence doesn't drift.
      let next = computeNextRun(rule.recurrence_type, rule.recurrence_value, new Date(rule.next_run_at));
      // Skip any missed slots so we don't loop on a far-past next_run_at.
      let guard = 0;
      while (next.getTime() <= Date.now() && guard++ < 2000) {
        next = computeNextRun(rule.recurrence_type, rule.recurrence_value, next);
      }
      // Safety net: never persist a next_run_at that is already due.
      if (next.getTime() <= Date.now()) {
        next = computeNextRun(rule.recurrence_type, rule.recurrence_value, new Date());
      }
      await es.update({
        index: 'recurrence_rules',
        id: rule.id,
        doc: { last_generated_at: nowIso(), next_run_at: next.toISOString() },
        refresh: 'wait_for',
      });
    } catch (e) {
      console.error(`[recurrence] rule ${rule.id} failed: ${e.message}`);
    }
  }
}

// Kick off the 5-minute scheduler (plus an immediate first pass).
export function startRecurrenceScheduler() {
  const tick = () => generateDueInstances().catch((e) => console.error('[recurrence]', e.message));
  setTimeout(tick, 8000); // shortly after boot, once ES is reachable
  setInterval(tick, 5 * 60 * 1000);
}
